export const data = [
  {
    name: 'Oladapo Benjamin',
    estimated_tank_storage: '12kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: 'Today, 19:40',
    gas_level: {
      level: 'full',
      amount: '12/12kg',
    },
    image: '/assets/images/avatar-1.png',
    status: 'in progress',
  },
  {
    name: 'Hassan Obi Adekunle',
    estimated_tank_storage: '12kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: 'Yesterday',
    gas_level: {
      level: 'mid',
      amount: '8/12kg',
    },
    image: '/assets/images/avatar-2.png',
    status: 'completed',
  },
  {
    name: 'Lana Adeyose',
    estimated_tank_storage: '25kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: '19 Aug 22',
    gas_level: {
      level: 'low',
      amount: '5/25kg',
    },
    image: '/assets/images/avatar-3.png',
    status: 'approved',
  },
  {
    name: 'Bimpe Craig',
    estimated_tank_storage: '12kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: '18 Aug 22',
    gas_level: {
      level: 'low',
      amount: '2/5kg',
    },
    image: '/assets/images/avatar-4.png',
    status: 'rejected',
  },
  {
    name: 'Ochuko Nedu',
    estimated_tank_storage: '12kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: '15 Aug 2022',
    gas_level: {
      level: 'low',
      amount: '2/12kg',
    },
    image: '/assets/images/avatar-5.png',
    status: 'in progress',
  },
  {
    name: 'Folashade Obilade',
    estimated_tank_storage: '600kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: 'Today, 19:40',
    gas_level: {
      level: 'full',
      amount: '600/600kg',
    },
    retailer: true,
    image: '/assets/images/avatar-1.png',
    status: 'approved',
  },
  {
    name: 'Adeoti Mary',
    estimated_tank_storage: '6kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: 'Yesterday',
    gas_level: {
      level: 'full',
      amount: '6/6kg',
    },
    image: '/assets/images/avatar-2.png',
    status: 'pending',
  },
  {
    name: 'Uche Jephtah',
    estimated_tank_storage: '2.5kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: '19 Aug 22',
    gas_level: {
      level: 'mid',
      amount: '1.5/2.5kg',
    },
    image: '/assets/images/avatar-3.png',
    status: 'pending',
  },
  {
    name: 'Femi Oludare',
    estimated_tank_storage: '600kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: '18 Aug 22',
    gas_level: {
      level: 'low',
      amount: '25/600kg',
    },
    retailer: true,
    image: '/assets/images/avatar-4.png',
    status: 'pending',
  },
  {
    name: 'Johnson Bagoni',
    estimated_tank_storage: '450kg',
    address: '5, Abifarin street, Ogudu GRA',
    last_order: '15 Aug 22',
    gas_level: {
      level: 'low',
      amount: '52/450kg',
    },
    retailer: true,
    image: '/assets/images/avatar-5.png',
    status: 'completed',
  },
];
